# Module: Pandas Assignments
## Lesson: Pandas
### Assignment 1: DataFrame Creation and Indexing

1. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Set the index to be the first column.
2. Create a Pandas DataFrame with columns 'A', 'B', 'C' and index 'X', 'Y', 'Z'. Fill the DataFrame with random integers and access the element at row 'Y' and column 'B'.

### Assignment 2: DataFrame Operations

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Add a new column that is the product of the first two columns.
2. Create a Pandas DataFrame with 3 columns and 4 rows filled with random integers. Compute the row-wise and column-wise sum.

### Assignment 3: Data Cleaning

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Introduce some NaN values. Fill the NaN values with the mean of the respective columns.
2. Create a Pandas DataFrame with 4 columns and 6 rows filled with random integers. Introduce some NaN values. Drop the rows with any NaN values.

### Assignment 4: Data Aggregation

1. Create a Pandas DataFrame with 2 columns: 'Category' and 'Value'. Fill the 'Category' column with random categories ('A', 'B', 'C') and the 'Value' column with random integers. Group the DataFrame by 'Category' and compute the sum and mean of 'Value' for each category.
2. Create a Pandas DataFrame with 3 columns: 'Product', 'Category', and 'Sales'. Fill the DataFrame with random data. Group the DataFrame by 'Category' and compute the total sales for each category.

### Assignment 5: Merging DataFrames

1. Create two Pandas DataFrames with a common column. Merge the DataFrames using the common column.
2. Create two Pandas DataFrames with different columns. Concatenate the DataFrames along the rows and along the columns.

### Assignment 6: Time Series Analysis

1. Create a Pandas DataFrame with a datetime index and one column filled with random integers. Resample the DataFrame to compute the monthly mean of the values.
2. Create a Pandas DataFrame with a datetime index ranging from '2021-01-01' to '2021-12-31' and one column filled with random integers. Compute the rolling mean with a window of 7 days.

### Assignment 7: MultiIndex DataFrame

1. Create a Pandas DataFrame with a MultiIndex (hierarchical index). Perform some basic indexing and slicing operations on the MultiIndex DataFrame.
2. Create a Pandas DataFrame with MultiIndex consisting of 'Category' and 'SubCategory'. Fill the DataFrame with random data and compute the sum of values for each 'Category' and 'SubCategory'.

### Assignment 8: Pivot Tables

1. Create a Pandas DataFrame with columns 'Date', 'Category', and 'Value'. Create a pivot table to compute the sum of 'Value' for each 'Category' by 'Date'.
2. Create a Pandas DataFrame with columns 'Year', 'Quarter', and 'Revenue'. Create a pivot table to compute the mean 'Revenue' for each 'Quarter' by 'Year'.

### Assignment 9: Applying Functions

1. Create a Pandas DataFrame with 3 columns and 5 rows filled with random integers. Apply a function that doubles the values of the DataFrame.
2. Create a Pandas DataFrame with 3 columns and 6 rows filled with random integers. Apply a lambda function to create a new column that is the sum of the existing columns.

### Assignment 10: Working with Text Data

1. Create a Pandas Series with 5 random text strings. Convert all the strings to uppercase.
2. Create a Pandas Series with 5 random text strings. Extract the first three characters of each string.

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame(
    np.random.randint(1,100,size=(6,4)),
    columns=['A','B','C','D']
)
df.set_index('A',inplace=True)
df

     B   C   D
A
79   1  52  76
12  73  50  63
79  44  66  62
3   42  95   4
29  59  34  81
36  67  74  78

In [4]:
df2 = pd.DataFrame(
    np.random.randint(1,100,size=(3,3)),
    index = ["X","Y","Z"],
    columns=["A","B","C"]
)
df2

    A   B   C
X  99  39  20
Y  53  75  51
Z  24  40  78

In [5]:
element = df2.loc["Y","B"]
print(element)

75

In [6]:
df3 = pd.DataFrame(
    np.random.randint(1,100,size=(5,3)),
    columns=['A','B','C']
)
df3

    A   B   C
0  53  81  10
1  42  38  29
2  99   5  46
3  68  83  68
4  39  99  16

In [7]:
df3['D'] = df3['A'] * df3['B']
df3

    A   B   C     D
0  53  81  10  4293
1  42  38  29  1596
2  99   5  46   495
3  68  83  68  5644
4  39  99  16  3861

In [8]:
df4 = pd.DataFrame(
    np.random.randint(1,100,size=(3,4)),
    columns = ['A','B','C','D']
)
df4

    A   B   C   D
0  89  17  48  96
1  75  71  75  75
2  91  93  79  10

In [9]:
row_sum = df4.sum(axis=1)
col_sum = df4.sum()
df4['Row Sum'] = row_sum
df4.loc['Col Sum'] = col_sum
df4

             A      B      C      D  Row Sum
0         89.0   17.0   48.0   96.0    250.0
1         75.0   71.0   75.0   75.0    296.0
2         91.0   93.0   79.0   10.0    273.0
Col Sum  255.0  181.0  202.0  181.0      NaN

In [10]:
df5 = pd.DataFrame(
    np.random.randint(1,100,size=(5,3)),
    columns=['A','B','C']
)
df5

    A   B   C
0  28  47  82
1  18  95  14
2  51  37  59
3  38   4  97
4  48  75  26

In [11]:
nan_percentage = 0.25 # 25% of NaN values we are adding
mask = np.random.rand(*df5.shape) < nan_percentage
df5 = df5.mask(mask)
df5 # Caution : The more you run this cell the more values get masked by NaN

    A     B   C
0  28   NaN  82
1  18  95.0  14
2  51  37.0  59
3  38   NaN  97
4  48  75.0  26

In [12]:
df5.isna().sum()

A    0
B    2
C    0
dtype: int64

In [13]:
df5 = df5.fillna(round(df5.mean(),2))

In [14]:
df5

    A     B   C
0  28  69.0  82
1  18  95.0  14
2  51  37.0  59
3  38  69.0  97
4  48  75.0  26

In [15]:
df6 = pd.DataFrame(
    np.random.randint(1,100,size=(6,4)),
    columns=['A','B','C','D']
)

In [16]:
df6

    A   B   C   D
0  57  32  55  65
1  67   2  80  57
2  13  79  68  55
3  12  64  53  99
4  88   7  47  17
5  38  66  18  38

In [17]:
nan_percent_for_df6 = 0.25
mask = np.random.rand(*df6.shape) < nan_percent_for_df6
df6 = df6.mask(mask)
df6

    A     B     C     D
0  57  32.0   NaN   NaN
1  67   2.0  80.0  57.0
2  13  79.0   NaN  55.0
3  12   NaN  53.0  99.0
4  88   7.0   NaN  17.0
5  38  66.0  18.0  38.0

In [18]:
df6 = df6.dropna()
df6

    A     B     C     D
1  67   2.0  80.0  57.0
5  38  66.0  18.0  38.0

### Data Aggregation Questions

In [19]:
df7 = pd.DataFrame({
    'Categories':np.random.choice(['A','B','C'],size=15),
    'Values':np.random.randint(1,100,size=15)
})
df7

   Categories  Values
0           C      82
1           A      71
2           B      21
3           B      76
4           A      96
5           C      43
6           B      32
7           C      83
8           B      91
9           B      98
10          A      37
11          A      84
12          A      64
13          C      57
14          A      40

In [20]:
grouped_data = df7.groupby('Categories')['Values'].agg(['sum','mean'])
grouped_data

            sum       mean
Categories
A           392  65.333333
B           318  63.600000
C           265  66.250000

In [21]:
df8 = pd.DataFrame({
    "Product": np.random.choice(
        ["Laptop", "Phone", "Tablet", "Headphones", "Camera", "Speaker"],
        size=20
    ),
    "Category": np.random.choice(
        ["Electronics", "Accessories", "Gadgets"],
        size=20
    ),
    "Sales": np.random.randint(1000, 50000, size=20)
})

In [22]:
sales_grouped = df8.groupby("Category")["Sales"].sum()
sales_grouped

Category
Accessories    195045
Electronics    143191
Gadgets         81807
Name: Sales, dtype: int32

### Merging DataFrames

In [ ]:
df8 = pd.DataFrame({
    "Products":np.random.choice(["Laptop", "Phone", "Tablet", "Headphones", "Camera", "Speaker"],size=20),
    "Categories":np.random.choice(["Electronics", "Accessories", "Gadgets"],size=20)
})