# Data Preprocessing

# 1. Handling missing values

In [30]:
import pandas as pd
import numpy as np
import yfinance as yf

In [4]:
data = {
    'Date': ['2024-01-01', '2024-01-02', '2024-01-04', '2024-01-07', '2024-01-08', '2024-01-09', '2024-01-10', '2024-01-12'],
    'Price': [100, 101, 103, 106, 107, 108, 109, 111]
}

# Create a DataFrame
data = pd.DataFrame(data)
data['Date'] = pd.to_datetime(data['Date'])
data.set_index('Date', inplace=True)

data

            Price
Date
2024-01-01    100
2024-01-02    101
2024-01-04    103
2024-01-07    106
2024-01-08    107
2024-01-09    108
2024-01-10    109
2024-01-12    111

In [5]:
# Create a complete date range
complete_index = pd.date_range(start='2024-01-01', end='2024-01-12', freq='D')

# Reindex the DataFrame
data = data.reindex(complete_index)

print("Reindexed DataFrame with Missing Dates:\n", data)

Reindexed DataFrame with Missing Dates:
             Price
2024-01-01  100.0
2024-01-02  101.0
2024-01-03    NaN
2024-01-04  103.0
2024-01-05    NaN
2024-01-06    NaN
2024-01-07  106.0
2024-01-08  107.0
2024-01-09  108.0
2024-01-10  109.0
2024-01-11    NaN
2024-01-12  111.0

# 1.1 Using IMPUTATION

In [12]:
# Mean Imputation
mean_value = data.mean()
data_mean_imputed = data.fillna(mean_value)

# Median Imputation
median_value = data.median()
data_median_imputed = data.fillna(median_value)

# Mode Imputation
mode_value = data.mode().iloc[0]
data_mode_imputed = data.fillna(mode_value.values[0])

# Forward Fill
data_ffill = data.ffill()

# Backward Fill
data_bfill = data.bfill()

print("Original Data:\n", data)
print("-----------\nMean:", mean_value.values[0])
print("-----------\nMean Imputation:\n", data_mean_imputed)
print("-----------\nMedian:", median_value.values[0])
print("-----------\nMedian Imputation:\n", data_median_imputed)
print("-----------\nMode:", mode_value.values[0])
print("-----------\nMode Imputation:\n", data_mode_imputed)
print("-----------\nForward Fill:\n", data_ffill)
print("-----------\nBackward Fill:\n", data_bfill)

Original Data:
             Price
2024-01-01  100.0
2024-01-02  101.0
2024-01-03    NaN
2024-01-04  103.0
2024-01-05    NaN
2024-01-06    NaN
2024-01-07  106.0
2024-01-08  107.0
2024-01-09  108.0
2024-01-10  109.0
2024-01-11    NaN
2024-01-12  111.0
-----------
Mean: 105.625
-----------
Mean Imputation:
               Price
2024-01-01  100.000
2024-01-02  101.000
2024-01-03  105.625
2024-01-04  103.000
2024-01-05  105.625
2024-01-06  105.625
2024-01-07  106.000
2024-01-08  107.000
2024-01-09  108.000
2024-01-10  109.000
2024-01-11  105.625
2024-01-12  111.000
-----------
Median: 106.5
-----------
Median Imputation:
             Price
2024-01-01  100.0
2024-01-02  101.0
2024-01-03  106.5
2024-01-04  103.0
2024-01-05  106.5
2024-01-06  106.5
2024-01-07  106.0
2024-01-08  107.0
2024-01-09  108.0
2024-01-10  109.0
2024-01-11  106.5
2024-01-12  111.0
-----------
Mode: 100.0
-----------
Mode Imputation:
             Price
2024-01-01  100.0
2024-01-02  101.0
2024-01-03  100.0
2024-01-04  103.0
2024-01-05  100.0
2024-01-06  100.0
2024-01-07  106.0
2024-01-08  107.0
2024-01-09  108.0
2024-01-10  109.0
2024-01-11  100.0
2024-01-12  111.0
-----------
Forward Fill:
             Price
2024-01-01  100.0
2024-01-02  101.0
2024-01-03  101.0
2024-01-04  103.0
2024-01-05  103.0
2024-01-06  103.0
2024-01-07  106.0
2024-01-08  107.0
2024-01-09  108.0
2024-01-10  109.0
2024-01-11  109.0
2024-01-12  111.0
-----------
Backward Fill:
             Price
2024-01-01  100.0
2024-01-02  101.0
2024-01-03  103.0
2024-01-04  103.0
2024-01-05  106.0
2024-01-06  106.0
2024-01-07  106.0
2024-01-08  107.0
2024-01-09  108.0
2024-01-10  109.0
2024-01-11  111.0
2024-01-12  111.0

# 1.2 Using INTERPOLATION

In [15]:
# Linear Interpolation
data_linear_interp = data.interpolate(method='linear')

# Polynomial Interpolation (degree 2)
data_poly_interp = data.interpolate(method='polynomial', order=2)

# Spline Interpolation (order 2)
data_spline_interp = data.interpolate(method='spline', order=2)

print("\nLinear Interpolation:\n", data_linear_interp)
print("\nPolynomial Interpolation (degree 2):\n", data_poly_interp)
print("\nSpline Interpolation (order 2):\n", data_spline_interp)

Linear Interpolation:
             Price
2024-01-01  100.0
2024-01-02  101.0
2024-01-03  102.0
2024-01-04  103.0
2024-01-05  104.0
2024-01-06  105.0
2024-01-07  106.0
2024-01-08  107.0
2024-01-09  108.0
2024-01-10  109.0
2024-01-11  110.0
2024-01-12  111.0

Polynomial Interpolation (degree 2):
             Price
2024-01-01  100.0
2024-01-02  101.0
2024-01-03  102.0
2024-01-04  103.0
2024-01-05  104.0
2024-01-06  105.0
2024-01-07  106.0
2024-01-08  107.0
2024-01-09  108.0
2024-01-10  109.0
2024-01-11  110.0
2024-01-12  111.0

Spline Interpolation (order 2):
             Price
2024-01-01  100.0
2024-01-02  101.0
2024-01-03  102.0
2024-01-04  103.0
2024-01-05  104.0
2024-01-06  105.0
2024-01-07  106.0
2024-01-08  107.0
2024-01-09  108.0
2024-01-10  109.0
2024-01-11  110.0
2024-01-12  111.0

In [17]:
data['Sales'] = [700, 900, 1000, 2000, 1500, 3000, 2300, 4000, 5900, 6000, 65000, 7000]
data

            Price  Sales
2024-01-01  100.0    700
2024-01-02  101.0    900
2024-01-03    NaN   1000
2024-01-04  103.0   2000
2024-01-05    NaN   1500
2024-01-06    NaN   3000
2024-01-07  106.0   2300
2024-01-08  107.0   4000
2024-01-09  108.0   5900
2024-01-10  109.0   6000
2024-01-11    NaN  65000
2024-01-12  111.0   7000

In [19]:
from sklearn.linear_model import LinearRegression

known_data = data.dropna(subset=['Price'])
missing_data = data[data['Price'].isna()]

# Train a model on known data
model = LinearRegression()
model.fit(known_data[['Sales']], known_data['Price'])

# Predict missing values
predicted_values = model.predict(missing_data[['Sales']])
data.loc[data['Price'].isna(), 'Price'] = predicted_values

print("\nData with Predicted Values:\n", data)

Data with Predicted Values:
                  Price  Sales
2024-01-01  100.000000    700
2024-01-02  101.000000    900
2024-01-03  101.675094   1000
2024-01-04  103.000000   2000
2024-01-05  102.434691   1500
2024-01-06  104.713483   3000
2024-01-07  106.000000   2300
2024-01-08  107.000000   4000
2024-01-09  108.000000   5900
2024-01-10  109.000000   6000
2024-01-11  198.903558  65000
2024-01-12  111.000000   7000

# Resampling

# 1. Downsampling

In [32]:
stock_data = yf.download('AAPL',start='2024-01-01')

[*********************100%***********************]  1 of 1 completed

In [41]:
monthly_data = stock_data['Close'].resample('ME').mean()
print("\nMonthly Downsampled Data:\n", monthly_data)

Monthly Downsampled Data:
 Ticker            AAPL
Date
2024-01-31  185.968012
2024-02-29  183.209133
2024-03-31  171.299133
2024-04-30  168.232190
2024-05-31  184.952322
2024-06-30  204.871686
2024-07-31  223.083471
2024-08-31  220.319721
2024-09-30  222.505752
2024-10-31  228.768595
2024-11-30  226.723620
2024-12-31  248.200304
2025-01-31  233.530800
2025-02-28  237.634378
2025-03-31  221.943917
2025-04-30  200.498205
2025-05-31  203.431011
2025-06-30  200.235423
2025-07-31  210.837013
2025-08-31  224.361021
2025-09-30  242.251352
2025-10-31  258.045067
2025-11-30  271.587632
2025-12-31  276.306362
2026-01-31  260.089163

# 2. Upsampling

In [44]:
hourly_data = stock_data['Close'].resample('h').interpolate(method='linear')
print("\nHourly Upsampled Data:\n", hourly_data)

Hourly Upsampled Data:
 Ticker                     AAPL
Date
2024-01-02 00:00:00  183.903244
2024-01-02 01:00:00  183.845869
2024-01-02 02:00:00  183.788494
2024-01-02 03:00:00  183.731119
2024-01-02 04:00:00  183.673744
...                         ...
2026-01-19 20:00:00  247.067914
2026-01-19 21:00:00  246.975935
2026-01-19 22:00:00  246.883955
2026-01-19 23:00:00  246.791976
2026-01-20 00:00:00  246.699997

[17977 rows x 1 columns]